package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallIntegralRule;
import org.linlinjava.litemall.db.domain.LitemallIntegralRuleExample;

public interface LitemallIntegralRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    long countByExample(LitemallIntegralRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallIntegralRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    int insert(LitemallIntegralRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    int insertSelective(LitemallIntegralRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegralRule selectOneByExample(LitemallIntegralRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegralRule selectOneByExampleSelective(@Param("example") LitemallIntegralRuleExample example, @Param("selective") LitemallIntegralRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallIntegralRule> selectByExampleSelective(@Param("example") LitemallIntegralRuleExample example, @Param("selective") LitemallIntegralRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    List<LitemallIntegralRule> selectByExample(LitemallIntegralRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegralRule selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallIntegralRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    LitemallIntegralRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallIntegralRule record, @Param("example") LitemallIntegralRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallIntegralRule record, @Param("example") LitemallIntegralRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallIntegralRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integral_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallIntegralRule record);
}