package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallIntegrals;
import org.linlinjava.litemall.db.domain.LitemallIntegralsExample;

public interface LitemallIntegralsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    long countByExample(LitemallIntegralsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallIntegralsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    int insert(LitemallIntegrals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    int insertSelective(LitemallIntegrals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegrals selectOneByExample(LitemallIntegralsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegrals selectOneByExampleSelective(@Param("example") LitemallIntegralsExample example, @Param("selective") LitemallIntegrals.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallIntegrals> selectByExampleSelective(@Param("example") LitemallIntegralsExample example, @Param("selective") LitemallIntegrals.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    List<LitemallIntegrals> selectByExample(LitemallIntegralsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallIntegrals selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallIntegrals.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    LitemallIntegrals selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallIntegrals record, @Param("example") LitemallIntegralsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallIntegrals record, @Param("example") LitemallIntegralsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallIntegrals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_integrals
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallIntegrals record);
}