package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class LitemallUsergrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_usergrade.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_usergrade.grade_name
     *
     * @mbg.generated
     */
    private String gradeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_usergrade.integral_multiple
     *
     * @mbg.generated
     */
    private Integer integralMultiple;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_usergrade.limit_of_integration
     *
     * @mbg.generated
     */
    private String limitOfIntegration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_usergrade.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_usergrade.id
     *
     * @return the value of litemall_usergrade.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_usergrade.id
     *
     * @param id the value for litemall_usergrade.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_usergrade.grade_name
     *
     * @return the value of litemall_usergrade.grade_name
     *
     * @mbg.generated
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_usergrade.grade_name
     *
     * @param gradeName the value for litemall_usergrade.grade_name
     *
     * @mbg.generated
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_usergrade.integral_multiple
     *
     * @return the value of litemall_usergrade.integral_multiple
     *
     * @mbg.generated
     */
    public Integer getIntegralMultiple() {
        return integralMultiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_usergrade.integral_multiple
     *
     * @param integralMultiple the value for litemall_usergrade.integral_multiple
     *
     * @mbg.generated
     */
    public void setIntegralMultiple(Integer integralMultiple) {
        this.integralMultiple = integralMultiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_usergrade.limit_of_integration
     *
     * @return the value of litemall_usergrade.limit_of_integration
     *
     * @mbg.generated
     */
    public String getLimitOfIntegration() {
        return limitOfIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_usergrade.limit_of_integration
     *
     * @param limitOfIntegration the value for litemall_usergrade.limit_of_integration
     *
     * @mbg.generated
     */
    public void setLimitOfIntegration(String limitOfIntegration) {
        this.limitOfIntegration = limitOfIntegration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_usergrade.remark
     *
     * @return the value of litemall_usergrade.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_usergrade.remark
     *
     * @param remark the value for litemall_usergrade.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usergrade
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gradeName=").append(gradeName);
        sb.append(", integralMultiple=").append(integralMultiple);
        sb.append(", limitOfIntegration=").append(limitOfIntegration);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usergrade
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallUsergrade other = (LitemallUsergrade) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGradeName() == null ? other.getGradeName() == null : this.getGradeName().equals(other.getGradeName()))
            && (this.getIntegralMultiple() == null ? other.getIntegralMultiple() == null : this.getIntegralMultiple().equals(other.getIntegralMultiple()))
            && (this.getLimitOfIntegration() == null ? other.getLimitOfIntegration() == null : this.getLimitOfIntegration().equals(other.getLimitOfIntegration()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_usergrade
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGradeName() == null) ? 0 : getGradeName().hashCode());
        result = prime * result + ((getIntegralMultiple() == null) ? 0 : getIntegralMultiple().hashCode());
        result = prime * result + ((getLimitOfIntegration() == null) ? 0 : getLimitOfIntegration().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_usergrade
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        gradeName("grade_name", "gradeName", "VARCHAR", false),
        integralMultiple("integral_multiple", "integralMultiple", "INTEGER", false),
        limitOfIntegration("limit_of_integration", "limitOfIntegration", "VARCHAR", false),
        remark("remark", "remark", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_usergrade
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}